[pytest]

addopts = -v -rx --alluredir=./allure-results

markers =
    positive_test: marker for positive test
    negative_test: marker for negative test
    smoke_test: marker for smoke test

    add_customer_page: marker for add customer page
    open_account_page: marker for open account page
    customers_page: marker for customers page